image: corise/dbt-course-gitpod
tasks:
  - command:
      sudo /etc/init.d/postgresql start
      export PGPASSWORD=corise PGUSER=corise PGDATABASE=dbt
      mkdir -p /workspace/.dbt && ln -snf /workspace/.dbt ~/.dbt
ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - cweijan.vscode-database-client2
